create table if not exists restaurants (
  id text primary key,
  name text not null,
  area text,
  address text,
  latitude double precision,
  longitude double precision,
  foursquare_place_id text,
  created_at timestamptz not null default now()
);

create table if not exists reviews (
  id text primary key,
  restaurant_id text not null references restaurants(id) on delete cascade,
  star_rating numeric not null check (star_rating >= 0 and star_rating <= 5),
  sentiment_score numeric check (sentiment_score is null or (sentiment_score >= 0 and sentiment_score <= 5)),
  recommendation_score numeric not null check (recommendation_score >= 0 and recommendation_score <= 5),
  review_text text not null,
  service_rating numeric check (service_rating is null or (service_rating >= 0 and service_rating <= 5)),
  service_vibe text,
  wait_time text,
  service_text text,
  ambiance text,
  recommended_dish text,
  must_try boolean not null default false,
  timestamp bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table reviews add column if not exists service_rating numeric check (service_rating is null or (service_rating >= 0 and service_rating <= 5));
alter table reviews add column if not exists service_vibe text;
alter table reviews add column if not exists wait_time text;
alter table reviews add column if not exists service_text text;
alter table reviews add column if not exists ambiance text;

create table if not exists review_cuisines (
  id bigint generated by default as identity primary key,
  review_id text not null references reviews(id) on delete cascade,
  cuisine text not null,
  created_at timestamptz not null default now(),
  unique(review_id, cuisine)
);

create table if not exists dishes (
  id text primary key,
  review_id text not null references reviews(id) on delete cascade,
  name text not null,
  rating numeric not null default 0 check (rating >= 0 and rating <= 5),
  review_text text,
  photo text,
  created_at timestamptz not null default now()
);

create index if not exists restaurants_name_idx on restaurants(name);
create index if not exists reviews_restaurant_id_idx on reviews(restaurant_id);
create index if not exists reviews_timestamp_idx on reviews(timestamp desc);
create index if not exists review_cuisines_review_id_idx on review_cuisines(review_id);
create index if not exists dishes_review_id_idx on dishes(review_id);

alter table restaurants enable row level security;
alter table reviews enable row level security;
alter table review_cuisines enable row level security;
alter table dishes enable row level security;

drop policy if exists "Public can read restaurants" on restaurants;
drop policy if exists "Public can read reviews" on reviews;
drop policy if exists "Public can read review cuisines" on review_cuisines;
drop policy if exists "Public can read dishes" on dishes;
drop policy if exists "Phase 1 can manage restaurants" on restaurants;
drop policy if exists "Phase 1 can manage reviews" on reviews;
drop policy if exists "Phase 1 can manage review cuisines" on review_cuisines;
drop policy if exists "Phase 1 can manage dishes" on dishes;

create policy "Public can read restaurants"
  on restaurants for select
  using (true);

create policy "Public can read reviews"
  on reviews for select
  using (true);

create policy "Public can read review cuisines"
  on review_cuisines for select
  using (true);

create policy "Public can read dishes"
  on dishes for select
  using (true);

-- Temporary Phase 1 write access for the hidden /nush route.
-- Replace these with authenticated/admin-only policies before adding public likes/comments.
create policy "Phase 1 can manage restaurants"
  on restaurants for all
  using (true)
  with check (true);

create policy "Phase 1 can manage reviews"
  on reviews for all
  using (true)
  with check (true);

create policy "Phase 1 can manage review cuisines"
  on review_cuisines for all
  using (true)
  with check (true);

create policy "Phase 1 can manage dishes"
  on dishes for all
  using (true)
  with check (true);
